version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.15.0

    working_directory: ~/dom-query

    steps:
      - checkout

      - run:
          name: Install Javascript dependencies
          command: pnpm install --frozen-lockfile

      - run:
          name: Typecheck sources (TypeScript)
          command: pnpm tsc

      - run:
          name: Lint js
          command: pnpm lint:js

      - run:
          name: "Tests"
          command: pnpm test
